name: CI
on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Setup go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Install lint
        run: |
          # binary will be $(go env GOPATH)/bin/golangci-lint
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.2
      - name: Run lint
        run: |
          golangci-lint run --timeout 5m

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Setup go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Set up github environment variables
        uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go get -d ./...
      - name: build
        run: |
          make build

